version: "3.8"

services:
  dapp:
    container_name: dapp
    build: .
    image: dapp
    volumes:
      - .:/dapp/
    ports:
      - "3000:3000"
    command: tail -F anything
  ganache:
    container_name: ganache
    image: trufflesuite/ganache-cli:latest
    command: --chainId=1336
    ports:
      - "7545:8545"